version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - ${PORT:-8080}:80
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST:-localhost}
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

volumes:
  wordpress:
