version: '3.1'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - wordpress
    restart: always
    environment:
      STAGE: ${STAGE:-staging}
      DOMAINS: '${DOMAIN:-example.com} -> http://wordpress:80'
      # STAGE: 'production' # Don't use production until staging works
      # FORCE_RENEW: 'true'

  wordpress:
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST:-localhost}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-wordpress}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-wordpress}
    volumes:
      - wordpress:/var/www/html

volumes:
  wordpress:
